
package batchPagos.arServices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
//Produccion
@WebServiceClient(name = "ArServicesHttpService", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", wsdlLocation = "http://iib.telcel.com:1730/mexico/telcel/di/sds/bes/cbs/arservices/v1?WSDL")
//Pre produccion
//@WebServiceClient(name = "ArServicesHttpService", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", wsdlLocation = "http://iib.telcel.com:1722/mexico/telcel/di/sds/bes/cbs/arservices/v1?WSDL")
public class ArServicesHttpService
    extends Service
{

    private final static URL ARSERVICESHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ARSERVICESHTTPSERVICE_EXCEPTION;
    private final static QName ARSERVICESHTTPSERVICE_QNAME = new QName("http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", "ArServicesHttpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//        	Produccion
            url = new URL("http://iib.telcel.com:1730/mexico/telcel/di/sds/bes/cbs/arservices/v1?WSDL");
//            Pre produccion
//            url = new URL("http://iib.telcel.com:1722/mexico/telcel/di/sds/bes/cbs/arservices/v1?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARSERVICESHTTPSERVICE_WSDL_LOCATION = url;
        ARSERVICESHTTPSERVICE_EXCEPTION = e;
    }

    public ArServicesHttpService() {
        super(__getWsdlLocation(), ARSERVICESHTTPSERVICE_QNAME);
    }

    public ArServicesHttpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARSERVICESHTTPSERVICE_QNAME);
    }

    public ArServicesHttpService(URL wsdlLocation) {
        super(wsdlLocation, ARSERVICESHTTPSERVICE_QNAME);
    }

    public ArServicesHttpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARSERVICESHTTPSERVICE_QNAME);
    }

    public ArServicesHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArServicesHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName );
    }

    /**
     * 
     * @return
     *     returns ArServices
     */
    @WebEndpoint(name = "ArServicesHttpPort")
    public ArServices getArServicesHttpPort() {
        return super.getPort(new QName("http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", "ArServicesHttpPort"), ArServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArServices
     */
    @WebEndpoint(name = "ArServicesHttpPort")
    public ArServices getArServicesHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", "ArServicesHttpPort"), ArServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARSERVICESHTTPSERVICE_EXCEPTION!= null) {
            throw ARSERVICESHTTPSERVICE_EXCEPTION;
        }
        return ARSERVICESHTTPSERVICE_WSDL_LOCATION;
    }

}
