
package batchPagos.arServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import batchPagos.controlData.ControlDataRequestHeaderType;
import batchPagos.controlData.ControlDataResponseHeaderType;
import batchPagos.controlData.DetailResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ArServices", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
@XmlSeeAlso({
	batchPagos.controlData.ObjectFactory.class,
	batchPagos.arServices.ObjectFactory.class
})
public interface ArServices {


    /**
     * 
     * @param detailResponse
     * @param adv2DepositResponse
     * @param controlData
     * @param adv2Deposit
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/adv2Deposit")
    @RequestWrapper(localName = "adv2Deposit", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.Adv2Deposit")
    @ResponseWrapper(localName = "adv2DepositResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.Adv2DepositResponse")
    public void adv2Deposit(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "adv2Deposit", targetNamespace = "")
        Adv2DepositPetType adv2Deposit,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "adv2DepositResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Adv2DepositRespType> adv2DepositResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param controlData
     * @param queryPaymentLog
     * @param queryPaymentLogResponse
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryPaymentLog")
    @RequestWrapper(localName = "queryPaymentLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryPaymentLog")
    @ResponseWrapper(localName = "queryPaymentLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryPaymentLogResponse")
    public void queryPaymentLog(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryPaymentLog", targetNamespace = "")
        QueryPaymentLogPetType queryPaymentLog,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryPaymentLogResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryPaymentLogRespType> queryPaymentLogResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param queryInvoiceResponse
     * @param queryInvoice
     * @param controlData
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryInvoice")
    @RequestWrapper(localName = "queryInvoice", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryInvoice")
    @ResponseWrapper(localName = "queryInvoiceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryInvoiceResponse")
    public void queryInvoice(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryInvoice", targetNamespace = "")
        QueryInvoicePetType queryInvoice,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryInvoiceResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryInvoiceRespType> queryInvoiceResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param queryInvoiceDetail
     * @param controlData
     * @param queryInvoiceDetailResponse
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryInvoiceDetail")
    @RequestWrapper(localName = "queryInvoiceDetail", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryInvoiceDetail")
    @ResponseWrapper(localName = "queryInvoiceDetailResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryInvoiceDetailResponse")
    public void queryInvoiceDetail(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryInvoiceDetail", targetNamespace = "")
        QueryInvoiceDetailPetType queryInvoiceDetail,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryInvoiceDetailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryInvoiceDetailRespType> queryInvoiceDetailResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param payment
     * @param paymentResponse
     * @param controlData
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/payment")
    @RequestWrapper(localName = "payment", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.Payment")
    @ResponseWrapper(localName = "paymentResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.PaymentResponse")
    public void payment(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "payment", targetNamespace = "")
        PaymentPetType payment,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "paymentResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<PaymentRespType> paymentResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param paymentRollBack
     * @param controlData
     * @param paymentRollBackResponse
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/paymentRollBack")
    @RequestWrapper(localName = "paymentRollBack", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.PaymentRollBack")
    @ResponseWrapper(localName = "paymentRollBackResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.PaymentRollBackResponse")
    public void paymentRollBack(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "paymentRollBack", targetNamespace = "")
        PaymentRollBackPetType paymentRollBack,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "paymentRollBackResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<PaymentRollBackRespType> paymentRollBackResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param refundResponse
     * @param refund
     * @param controlData
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/refund")
    @RequestWrapper(localName = "refund", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.Refund")
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.RefundResponse")
    public void refund(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "refund", targetNamespace = "")
        RefundPetType refund,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "refundResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<RefundRespType> refundResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param adjustmentResponse
     * @param adjustment
     * @param controlData
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/adjustment")
    @RequestWrapper(localName = "adjustment", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.Adjustment")
    @ResponseWrapper(localName = "adjustmentResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.AdjustmentResponse")
    public void adjustment(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "adjustment", targetNamespace = "")
        AdjustmentPetType adjustment,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "adjustmentResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<AdjustmentRespType> adjustmentResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param queryBalance
     * @param queryBalanceResponse
     * @param controlData
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryBalance")
    @RequestWrapper(localName = "queryBalance", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryBalance")
    @ResponseWrapper(localName = "queryBalanceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryBalanceResponse")
    public void queryBalance(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryBalance", targetNamespace = "")
        QueryBalancePetType queryBalance,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryBalanceResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryBalanceRespType> queryBalanceResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param queryCustomerArrears
     * @param controlData
     * @param queryCustomerArrearsResponse
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryCustomerArrears")
    @RequestWrapper(localName = "queryCustomerArrears", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryCustomerArrears")
    @ResponseWrapper(localName = "queryCustomerArrearsResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryCustomerArrearsResponse")
    public void queryCustomerArrears(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryCustomerArrears", targetNamespace = "")
        QueryCustomerArrearsPetType queryCustomerArrears,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryCustomerArrearsResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryCustomerArrearsRespType> queryCustomerArrearsResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param querySumBalanceAndCredit
     * @param controlData
     * @param querySumBalanceAndCreditResponse
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/querySumBalanceAndCredit")
    @RequestWrapper(localName = "querySumBalanceAndCredit", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QuerySumBalanceAndCredit")
    @ResponseWrapper(localName = "querySumBalanceAndCreditResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QuerySumBalanceAndCreditResponse")
    public void querySumBalanceAndCredit(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "querySumBalanceAndCredit", targetNamespace = "")
        QuerySumBalanceAndCreditPetType querySumBalanceAndCredit,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "querySumBalanceAndCreditResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QuerySumBalanceAndCreditRespType> querySumBalanceAndCreditResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param controlData
     * @param transferBalanceResponse
     * @param controlData0
     * @param transferBalance
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/transferBalance")
    @RequestWrapper(localName = "transferBalance", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.TransferBalance")
    @ResponseWrapper(localName = "transferBalanceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.TransferBalanceResponse")
    public void transferBalance(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "transferBalance", targetNamespace = "")
        TransferBalancePetType transferBalance,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "transferBalanceResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TransferBalanceRespType> transferBalanceResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param queryTransferLog
     * @param controlData
     * @param queryTransferLogResponse
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryTransferLog")
    @RequestWrapper(localName = "queryTransferLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryTransferLog")
    @ResponseWrapper(localName = "queryTransferLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryTransferLogResponse")
    public void queryTransferLog(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryTransferLog", targetNamespace = "")
        QueryTransferLogPetType queryTransferLog,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryTransferLogResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryTransferLogRespType> queryTransferLogResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param queryAdjustLogResponse
     * @param queryAdjustLog
     * @param controlData
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryAdjustLog")
    @RequestWrapper(localName = "queryAdjustLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryAdjustLog")
    @ResponseWrapper(localName = "queryAdjustLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryAdjustLogResponse")
    public void queryAdjustLog(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryAdjustLog", targetNamespace = "")
        QueryAdjustLogPetType queryAdjustLog,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryAdjustLogResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryAdjustLogRespType> queryAdjustLogResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param queryDepositBalance
     * @param controlData
     * @param queryDepositBalanceResponse
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryDepositBalance")
    @RequestWrapper(localName = "queryDepositBalance", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryDepositBalance")
    @ResponseWrapper(localName = "queryDepositBalanceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryDepositBalanceResponse")
    public void queryDepositBalance(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryDepositBalance", targetNamespace = "")
        QueryDepositBalancePetType queryDepositBalance,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryDepositBalanceResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryDepositBalanceRespType> queryDepositBalanceResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param controlData
     * @param queryRefundLogResponse
     * @param queryRefundLog
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryRefundLog")
    @RequestWrapper(localName = "queryRefundLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryRefundLog")
    @ResponseWrapper(localName = "queryRefundLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryRefundLogResponse")
    public void queryRefundLog(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryRefundLog", targetNamespace = "")
        QueryRefundLogPetType queryRefundLog,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryRefundLogResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryRefundLogRespType> queryRefundLogResponse)
        throws GeneralException
    ;

    /**
     * 
     * @param detailResponse
     * @param queryTransaction
     * @param queryTransactionResponse
     * @param controlData
     * @param controlData0
     * @throws GeneralException
     */
    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryTransaction")
    @RequestWrapper(localName = "queryTransaction", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryTransaction")
    @ResponseWrapper(localName = "queryTransactionResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", className = "mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.QueryTransactionResponse")
    public void queryTransaction(
        @WebParam(name = "controlData", targetNamespace = "")
        ControlDataRequestHeaderType controlData,
        @WebParam(name = "queryTransaction", targetNamespace = "")
        QueryTransactionPetType queryTransaction,
        @WebParam(name = "controlData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ControlDataResponseHeaderType> controlData0,
        @WebParam(name = "detailResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DetailResponseType> detailResponse,
        @WebParam(name = "queryTransactionResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<QueryTransactionRespType> queryTransactionResponse)
        throws GeneralException
    ;

}
