
package batchPagos.arServices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "generalException", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
public class GeneralException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ArServicesException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GeneralException(String message, ArServicesException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GeneralException(String message, ArServicesException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mx.com.amx.mexico.telcel.di.sds.bes.esb.arservices.ArServicesException
     */
    public ArServicesException getFaultInfo() {
        return faultInfo;
    }

}
